artifact_location: /Users/yashwanth/Documents/Projects/ref-0-hackathon/runs/mlflow/648294115144686025
creation_time: 1777621037690
experiment_id: '648294115144686025'
last_update_time: 1777621037690
lifecycle_stage: active
name: runs/detect
trace_location: null
workspace: default
