artifact_location: /Users/yashwanth/Documents/Projects/ref-0-hackathon/runs/mlflow/0
creation_time: 1777621037680
experiment_id: '0'
last_update_time: 1777621037680
lifecycle_stage: active
name: Default
trace_location: null
workspace: default
