artifact_uri: /Users/yashwanth/Documents/Projects/ref-0-hackathon/runs/mlflow/648294115144686025/c17d34507d0f483da9a9dfad2af924a9/artifacts
end_time: 1777879842577
entry_point_name: ''
experiment_id: '648294115144686025'
lifecycle_stage: active
run_id: c17d34507d0f483da9a9dfad2af924a9
run_name: yolo11m-ablation
source_name: ''
source_type: 4
source_version: ''
start_time: 1777838155051
status: 3
tags: []
user_id: yashwanth
